src/objects/LearningContent__c.object
<CustomObject>
    <fields>
        <fullName>TargetSkill__c</fullName>
        <description>対象とするスキルです</description>
        <label>対象スキル</label>
        <picklist>
            <picklistValues>
                <fullName>プログラミング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>エンジニアリング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>事務</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>全般</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>その他</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>学習コンテンツ</label>
    <nameField>
        <label>学習コンテンツ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LearningLog__c.object
<CustomObject>
    <fields>
        <fullName>LearningContent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>学習コンテンツ</label>
        <referenceTo>LearningContent__c</referenceTo>
        <relationshipLabel>学習予定記録</relationshipLabel>
        <relationshipName>LearningLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>学習予定記録</label>
    <nameField>
        <label>学習予定記録名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>InterestingSkill__c</fullName>
        <label>興味のあるスキル</label>
        <picklist>
            <picklistValues>
                <fullName>プログラミング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>エンジニアリング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>事務</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>全般</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>その他</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/classes/LearningContentServiceTest.cls
@IsTest
private class LearningContentServiceTest {

    static testMethod void testRecommend1() {
        LearningContent__c content = new LearningContent__c();
        content.Name = '学習コンテンツ';
        content.TargetSkill__c = 'プログラミング';
        insert content;
        
        Profile p = [SELECT Id, Name FROM Profile WHERE Name IN ('システム管理者', 'System Admin') LIMIT 1];

        User u = new User(
            FirstName='太郎',
            LastName='山田',
            InterestingSkill__c='プログラミング',
            Username='pl_test_user1@example.com',
            Email='pl_test_user1@example.com',
            Alias='山田 太郎',
            CommunityNickname='pl_test_user1',
            EmailEncodingKey='ISO-2022-JP',
            TimeZoneSidKey='Asia/Tokyo',
            LocaleSidKey='ja_JP',
            LanguageLocaleKey='ja',
            ProfileId=p.Id);
        insert u;
        LearningContentService.recommend(content.Id);
 
        List<LearningLog__c> logs = [SELECT Id, Name FROM LearningLog__c WHERE OwnerId = :u.Id];
        System.assertEquals(1, logs.size());
    }

    static testMethod void testRecommend2() {
        LearningContent__c content = new LearningContent__c();
        content.Name = '学習コンテンツ';
        content.TargetSkill__c = 'エンジニアリング';
        insert content;
        
        Profile p = [SELECT Id, Name FROM Profile WHERE Name IN ('システム管理者', 'System Admin') LIMIT 1];

        User u = new User(
            FirstName='太郎',
            LastName='山田',
            InterestingSkill__c='プログラミング',
            Username='pl_test_user1@example.com',
            Email='pl_test_user1@example.com',
            Alias='山田 太郎',
            CommunityNickname='pl_test_user1',
            EmailEncodingKey='ISO-2022-JP',
            TimeZoneSidKey='Asia/Tokyo',
            LocaleSidKey='ja_JP',
            LanguageLocaleKey='ja',
            ProfileId=p.Id);
        insert u;
        LearningContentService.recommend(content.Id);
 
        List<LearningLog__c> logs = [SELECT Id, Name FROM LearningLog__c WHERE OwnerId = :u.Id];
        System.assertEquals(0, logs.size());
    }

    static testMethod void testAssign1() {
        LearningContent__c content = new LearningContent__c();
        content.Name = '学習コンテンツ';
        content.TargetSkill__c = '';
        insert content;
        
        Profile p = [SELECT Id, Name FROM Profile WHERE Name IN ('システム管理者', 'System Admin') LIMIT 1];

        User u = new User(
            FirstName='太郎',
            LastName='山田',
            InterestingSkill__c='プログラミング',
            Username='pl_test_user1@example.com',
            Email='pl_test_user1@example.com',
            Alias='山田 太郎',
            CommunityNickname='pl_test_user1',
            EmailEncodingKey='ISO-2022-JP',
            TimeZoneSidKey='Asia/Tokyo',
            LocaleSidKey='ja_JP',
            LanguageLocaleKey='ja',
            ProfileId=p.Id);
        insert u;
        LearningContentService.assign(content.Id);
 
        List<LearningLog__c> logs = [SELECT Id, Name FROM LearningLog__c WHERE OwnerId = :u.Id];
        System.assertEquals(1, logs.size());
    }

}