src/objects/LearningContent__c.object
<CustomObject>
    <fields>
        <fullName>TargetSkill__c</fullName>
        <description>対象とするスキルです</description>
        <label>対象スキル</label>
        <picklist>
            <picklistValues>
                <fullName>プログラミング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>エンジニアリング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>事務</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>全般</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>その他</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>学習コンテンツ</label>
    <nameField>
        <label>学習コンテンツ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LearningLog__c.object
<CustomObject>
    <fields>
        <fullName>LearningContent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>学習コンテンツ</label>
        <referenceTo>LearningContent__c</referenceTo>
        <relationshipLabel>学習予定記録</relationshipLabel>
        <relationshipName>LearningLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>状況</label>
        <picklist>
            <picklistValues>
                <fullName>おすすめ！</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>学習予定</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>学習しました</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>学習しません</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>学習予定記録</label>
    <nameField>
        <label>学習予定記録名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>InterestingSkill__c</fullName>
        <label>興味のあるスキル</label>
        <picklist>
            <picklistValues>
                <fullName>プログラミング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>エンジニアリング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>事務</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>全般</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>その他</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/classes/LearningContentService.cls
global class LearningContentService {

    webService static boolean recommend(Id learningContentId) {
        List<LearningLog__c> logs = new List<LearningLog__c>();
 
         LearningContent__c content = [SELECT Id, Name, TargetSkill__c FROM LearningContent__c WHERE Id = :learningContentId LIMIT 1];
 
        for(User user : [SELECT Id, Name, InterestingSkill__c FROM User WHERE IsActive=true AND UserType IN ('標準', 'Standard')]) {
            if(user.InterestingSkill__c != null && user.InterestingSkill__c.contains(content.TargetSkill__c)) {
                LearningLog__c log = new LearningLog__c();
                log.OwnerId = user.id;
                log.Name = '学習記録' + content.Name + ' ' + user.Name;
                log.LearningContent__c = content.Id;
                log.Status__c = 'おすすめ！';
                logs.add(log);
            }
        }

        if(logs.size() > 0) Database.insert(logs);
        
        return true;
    }

    webService static boolean assign(Id learningContentId) {
        List<LearningLog__c> logs = new List<LearningLog__c>();
 
         LearningContent__c content = [SELECT Id, Name, TargetSkill__c FROM LearningContent__c WHERE Id = :learningContentId LIMIT 1];
 
        for(User user : [SELECT Id, Name, InterestingSkill__c FROM User WHERE IsActive=true AND UserType IN ('標準', 'Standard')]) {
            LearningLog__c log = new LearningLog__c();
            log.OwnerId = user.id;
            log.Name = '学習記録' + content.Name + ' ' + user.Name;
            log.LearningContent__c = content.Id;
            log.Status__c = 'おすすめ！';
            logs.add(log);
        }

        if(logs.size() > 0) Database.insert(logs);
        
        return true;
    }
 }